services:
    _defaults:
        public: false

    htc_strict_form_mapper.form_extension:
        class: HTC\StrictFormMapper\Form\Extension\StrictFormTypeExtension
        arguments: [!tagged htc_strict_form_mapper.voter]
        tags:
            - { name: form.type_extension, priority: -10 }


