<?php

declare(strict_types=1);

namespace HTC\StrictFormMapper;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;

class HTCStrictFormMapperBundle extends Bundle
{
    public function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }
}
